source 'https://rubygems.org'

gem 'rails', '4.0.0'

gem 'asset_sync'
gem 'bson_ext'
gem 'coffee-rails', '~> 4.0.0'
gem 'compass-rails'
gem 'curb'
gem 'decent_exposure'
gem 'figaro'
gem 'font-awesome-rails'
gem 'heroku-api'
gem 'jquery-rails'
gem 'mongoid', github: 'mongoid/mongoid'
gem 'newrelic_rpm'
gem 'omniauth-heroku'
gem 'sass-rails', '~> 4.0.0'
gem 'slim'
gem 'therubyracer', platforms: :ruby
gem 'thin'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
